### PR TITLE
Upgrade to Materialize 1.0.0

### PR DESCRIPTION
**Pull request by scote**
https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md

Upgrade guide
- [ ] Sidenav
- [ ] Tab
- [ ] Chips
- [ ] Dropdown
- [ ] Select
- [ ] Collections
- [ ] Floating Action Buttons
- [ ] Toasts

### CODE REVIEW

**Comment by jfcere** [comment]
I would like to participate in this upgrade. Before you go to far, I think we would need a better branching strategy to keep better track of the work done and not to do a single dump in master branch when it will be done.

**Comment by scote** [comment]
Good point, what we could to is doing our pull request on materialize-v1 branch during the upgrade and until it will be finished.

**Comment by jfcere** [comment]
My thought exactly.

```
- master
  - materialize-v1 (do not stash when merging to master)
    - component A (stash when merging to materialize-v1 - will keep only 1 commit for this component)
    - component B (same has component A)
    - etc...
```

This way we get...
- better follow-up on where we are
- keep track of who did what
- easier to work together

**Comment by scote** [comment]
I'm gonna close this pull request.

**Pull request closed without merging**
